# -*- coding: utf-8 -*-
"""Notebook0(academics).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJM7MpWbXRf0Hj-TcoHIGoNPwf6yE-rC

For nearly 30 years, ArXiv has served the public and research communities by providing open access to scholarly articles, from the vast branches of physics to the many subdisciplines of computer science to everything in between, including math, statistics, electrical engineering, quantitative biology, and economics. This rich corpus of information offers significant, but sometimes overwhelming depth.

In these times of unique global challenges, efficient extraction of insights from data is essential. To help make the arXiv more accessible, we present a free, open pipeline on Kaggle to the machine-readable arXiv dataset: a repository of 1.7 million articles, with relevant features such as article titles, authors, categories, abstracts, full text PDFs, and more.

Our hope is to empower new use cases that can lead to the exploration of richer machine learning techniques that combine multi-modal features towards applications like trend analysis, paper recommender engines, category prediction, co-citation networks, knowledge graph construction and semantic search interfaces.

The dataset is freely available via Google Cloud Storage buckets (more info here). Stay tuned for weekly updates to the dataset!

ArXiv is a collaboratively funded, community-supported resource founded by Paul Ginsparg in 1991 and maintained and operated by Cornell University.

The release of this dataset was featured further in a Kaggle blog post here.



See here for more information.

ArXiv On Kaggle
Metadata
This dataset is a mirror of the original ArXiv data. Because the full dataset is rather large (1.1TB and growing), this dataset provides only a metadata file in the json format. This file contains an entry for each paper, containing:

id: ArXiv ID (can be used to access the paper, see below)
submitter: Who submitted the paper
authors: Authors of the paper
title: Title of the paper
comments: Additional info, such as number of pages and figures
journal-ref: Information about the journal the paper was published in
doi: [https://www.doi.org](Digital Object Identifier)
abstract: The abstract of the paper
categories: Categories / tags in the ArXiv system
versions: A version history
You can access each paper directly on ArXiv using these links:

https://arxiv.org/abs/{id}: Page for this paper including its abstract and further links
https://arxiv.org/pdf/{id}: Direct link to download the PDF
Bulk access
The full set of PDFs is available for free in the GCS bucket gs://arxiv-dataset or through Google API (json documentation and xml documentation).

You can use for example gsutil to download the data to your local machine.

# List files:
gsutil cp gs://arxiv-dataset/arxiv/

# Download pdfs from March 2020:
gsutil cp gs://arxiv-dataset/arxiv/arxiv/pdf/2003/ ./a_local_directory/

# Download all the source files
gsutil cp -r gs://arxiv-dataset/arxiv/  ./a_local_directory/
Update Frequency
We're automatically updating the metadata as well as the GCS bucket on a weekly basis.

License
Creative Commons CC0 1.0 Universal Public Domain Dedication applies to the metadata in this dataset. See https://arxiv.org/help/license for further details and licensing on individual papers.

Acknowledgements
The original data is maintained by ArXiv, huge thanks to the team for building and maintaining this dataset.

We're using https://github.com/mattbierbaum/arxiv-public-datasets to pull the original data, thanks to Matt Bierbaum for providing this tool.
"""

# Instalación de dependencias necesarias en Google Colab
!pip install -q transformers peft bitsandbytes datasets accelerate

# Librerías necesarias para el desarrollo del primer entrenamiento
import os
import re

import torch
import matplotlib.pyplot as plt

from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
    set_seed,
)
from peft import LoraConfig, get_peft_model
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

set_seed(42)

BASE_PATH = "/content/drive/MyDrive/TFG 2025-2026"
MODELS_PATH = f"{BASE_PATH}/models"
DATA_REF_PATH = f"{BASE_PATH}/data_reference"

os.makedirs(MODELS_PATH, exist_ok=True)
os.makedirs(DATA_REF_PATH, exist_ok=True)

# Al ejecutarse es muy probable que de un aviso relacionado con: HF_TOKEN, esto es por que el token secreto no se ha configurado en GitHub
# Por cuestiones de seguridad no se configuró este ya que deja la descarga correcta del dataset

# Carga del dataset de abstarcts académicos desde Huggin Face
dataset = load_dataset("CShorten/ML-ArXiv-Papers", split="train")

print("Total original:", len(dataset))

# Parámetros de filtrado de abstracts
MIN_WORDS = 80
MAX_WORDS = 350

def clean_text(text):
    """
    Limpia el abstract eliminando artefactos básicos de LaTeX y normalizando espacios.
    """
    if text is None:
        return ""

    # Quitar comandos latex simples
    text = re.sub(r"\\[a-zA-Z]+\{.*?\}", "", text)
    text = re.sub(r"\$.*?\$", "", text)
    text = re.sub(r"\\[a-zA-Z]+", "", text)

    # Espacios múltiples
    text = re.sub(r"\s+", " ", text)

    return text.strip()

def build_text(example):
    """
    Conserva únicamente los abstracts con una longitud razonable para el entrenamiento.
    """
    abstract = clean_text(example["abstract"])
    words = abstract.split()

    if len(words) < MIN_WORDS or len(words) > MAX_WORDS:
        return {"text": ""}

    return {"text": f"Abstract: {abstract}"}

dataset = dataset.map(build_text)
dataset = dataset.filter(lambda x: len(x["text"]) > 0)
dataset = dataset.remove_columns([col for col in dataset.column_names if col != "text"])

print("Tras limpieza:", len(dataset))

dataset = dataset.shuffle(seed=42).select(range(10000))
print("Dataset final:", len(dataset))

# División del dataset en los conjuntos train y test

split = dataset.train_test_split(test_size=0.1, seed=42)
train_dataset = split["train"]
eval_dataset = split["test"]

print("Train:", len(train_dataset))
print("Eval:", len(eval_dataset))

# Comprobación de solapamiento entre train y eval
train_texts = set(train_dataset["text"])
eval_texts = set(eval_dataset["text"])

overlap = train_texts.intersection(eval_texts)

print("Textos repetidos entre train y eval:", len(overlap))

if len(overlap) > 0:
    print("Aviso: existen textos repetidos entre train y eval.")
else:
    print("No hay solapamiento entre train y eval.")

# Almacenamos el modelo en iter0 al ser la primera iteración tras el fine-tuning
train_dataset.to_json(f"{DATA_REF_PATH}/train_split_iter0.json")
eval_dataset.to_json(f"{DATA_REF_PATH}/test_split_iter0.json")

# Modelo utilizado en el desarrollo del proyecto

model_id = "mistralai/Mistral-7B-v0.1"

# Configuración emn 4 bits para reducir el uso de memoria GPU
# Gracias a esto, el modelo puede ser cargado en Google Colab usando bitsandbytes.
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

# Carga de tokenizador
tokenizer = AutoTokenizer.from_pretrained(model_id)

# En la documentación se menciona que Mistral no define un token de padding por lo que se reutiliza EOS.
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# Cargar el modelo base en 4 bits.
# device_map="auto" distribuye automáticamente el modelo en los recursos disponibles.
base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto"
)

def tokenize_fn(example):
    return tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=512
    )

# Configuración LoRA para realizar fine-tuning
# En lugar de entrenar todos los pesos, LoRA permite entrenar con matrices de peso de bajo rango
# Esta trabaja sobre módulos concretos de atención, reduciendo el coste computacional

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

# Aplicación de LoRA al modelo
model = get_peft_model(base_model, lora_config)

# Muestra el número de parámetros entrenables frente a los totales del modelo
model.print_trainable_parameters()

train_tok = train_dataset.map(tokenize_fn, batched=True)
eval_tok = eval_dataset.map(tokenize_fn, batched=True)

# Entrenamiento en el que Mistral aprende a predecir el siguiente token
data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./results_iter0_academic",
    per_device_train_batch_size=2,

    # El cálculo de Batch efectivo --> 2 * 4 = 8, lo cual reduce el consumo de memoria.
    gradient_accumulation_steps=4,

    # Una época para adaptar el modelo al domínio sin favorecer a la memorización.
    num_train_epochs=1,
    learning_rate=1e-4,

    # Precisión máxima para reducir GPU
    fp16=True,
    logging_steps=20,
    eval_strategy="steps",

    # No se guardan checkpoints intermedios para evitar ocupar almacenamiento
    save_strategy="no",
    report_to="none",

    # Optimizador de 8 bits como se comentó anteriormente para entrenar modelos grandes con menos memoria
    optim="paged_adamw_8bit",
    seed=42,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tok,
    eval_dataset=eval_tok,
    data_collator=data_collator,
)

trainer.train()

import matplotlib.pyplot as plt

logs = trainer.state.log_history

train_epochs = []
train_loss = []

eval_epochs = []
eval_loss = []

for entry in logs:
    if "loss" in entry and "epoch" in entry:
        train_epochs.append(entry["epoch"])
        train_loss.append(entry["loss"])
    if "eval_loss" in entry:
        eval_epochs.append(entry["epoch"])
        eval_loss.append(entry["eval_loss"])

# Visualización de la evolución de la pérdida durante el entrenamiento.
plt.figure()
plt.plot(train_epochs, train_loss, label="Training Loss")
plt.plot(eval_epochs, eval_loss, label="Validation Loss")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss Evolution (Iter0)")
plt.legend()
plt.show()

ITER0_SAVE_PATH = f"{MODELS_PATH}/iter0_academic"
os.makedirs(ITER0_SAVE_PATH, exist_ok=True)

# Se guardan los pesos LoRA entrenados y el tokenizador para reutilizarlos en las siguientes iteraciones.
model.save_pretrained(ITER0_SAVE_PATH)
tokenizer.save_pretrained(ITER0_SAVE_PATH)

print("Iter0 guardado en:", ITER0_SAVE_PATH)

# Generación de prueba con muestreo controlado para comprobar el comportamiento del modelo ajustado.

def generate_text(prompt, max_new_tokens=180):
    model.eval()
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.9,
            top_p=0.95,
            repetition_penalty=1.1,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.eos_token_id,
        )
    return tokenizer.decode(out[0], skip_special_tokens=True)

print("\n=== EJEMPLO ITER0 ===\n")
print(generate_text("Abstract: In this study,"))